package com.myspace.jbpm_elements_katas;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cost")
	private java.lang.Double cost;
	@org.kie.api.definition.type.Label("Delivery")
	private Delivery delivery;

	@org.kie.api.definition.type.Label(value = "Actions")
	private java.util.List<java.lang.String> actions;

	public Order() {
	}

	public java.lang.Double getCost() {
		return this.cost;
	}

	public void setCost(java.lang.Double cost) {
		this.cost = cost;
	}

	public com.myspace.jbpm_elements_katas.Delivery getDelivery() {
		return this.delivery;
	}

	public void setDelivery(com.myspace.jbpm_elements_katas.Delivery delivery) {
		this.delivery = delivery;
	}

	public java.util.List<java.lang.String> getActions() {
		return this.actions;
	}

	public void setActions(java.util.List<java.lang.String> actions) {
		this.actions = actions;
	}

	public Order(java.lang.Double cost,
			com.myspace.jbpm_elements_katas.Delivery delivery,
			java.util.List<java.lang.String> actions) {
		this.cost = cost;
		this.delivery = delivery;
		this.actions = actions;
	}

	public void addAction(String action) {
		if (this.actions == null) {
			this.actions = new ArrayList<String>();
		}
		this.actions.add(action);
	}

}